<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>{PAGE_TITLE} Photo Album</title>
<meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
<meta name="copyright" content="(c) {COPYRIGHT} MarchTwenty.com" />
<meta name="authors" content="Ted Balmer @ marchtwenty.com" />
<meta name="robots" content="noindex, nofollow" />
<style type="text/css" media="screen,projection,handheld">@import "{DOMAIN}/template/album.css";</style>
<link type="image/x-icon" rel="shortcut icon" href="{DOMAIN}/favicon.ico" />
</head>

<body>

<div id="Page">
	<div id="Header">
		<div id="Logo"></div>
		<h1>{SITE_TITLE}</h1>
		<dl>
			<dd><a href="javascript:history.go(-1)" class="back">Return to the previous page</a> | <a href="/">Home Page</a></dd>
		</dl>
	</div>

	<div id="PageTitle">{PAGE_TITLE}</div>

	<div id="Content">
{PAGE_CONTENT}
	</div>

	<!--div id="Footer">&copy; {COPYRIGHT} <a href="http://www.marchtwenty.com/services/">MarchTwenty.com</a></div-->
</div>

</body>
</html>