<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>{SITE_TITLE}</title>
<meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
<meta name="copyright" content="(c) {COPYRIGHT} March Twenty Productions" />
<meta name="authors" content="Ted Balmer @ marchtwenty.com" />
<style type="text/css" media="screen,projection,handheld">@import "{DOMAIN}/template/mstyle.css";</style>
<link type="image/x-icon" rel="shortcut icon" href="{DOMAIN}/favicon.ico" />
</head>

<body>

{CONTENT}

</body>
</html>